env:
  browser: true
  es2020: true
extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
rules: {
  no-console: 0
  import/extensions: 0
}
